/**
 * Map of country names to their primary timezone
 */
export const COUNTRY_TIMEZONE_MAP: Record<string, string> = {
  "United States": "America/New_York",
  "Canada": "America/Toronto",
  "Mexico": "America/Mexico_City",
  "Brazil": "America/Sao_Paulo",
  "Argentina": "America/Buenos_Aires",
  "Chile": "America/Santiago",
  "Colombia": "America/Bogota",
  "Peru": "America/Lima",
  "Venezuela": "America/Caracas",
  "Ecuador": "America/Guayaquil",
  "Bolivia": "America/La_Paz",
  "Paraguay": "America/Asuncion",
  "Uruguay": "America/Montevideo",
  "United Kingdom": "Europe/London",
  "Ireland": "Europe/Dublin",
  "France": "Europe/Paris",
  "Germany": "Europe/Berlin",
  "Spain": "Europe/Madrid",
  "Italy": "Europe/Rome",
  "Portugal": "Europe/Lisbon",
  "Netherlands": "Europe/Amsterdam",
  "Belgium": "Europe/Brussels",
  "Switzerland": "Europe/Zurich",
  "Austria": "Europe/Vienna",
  "Poland": "Europe/Warsaw",
  "Czech Republic": "Europe/Prague",
  "Greece": "Europe/Athens",
  "Sweden": "Europe/Stockholm",
  "Norway": "Europe/Oslo",
  "Denmark": "Europe/Copenhagen",
  "Finland": "Europe/Helsinki",
  "Russia": "Europe/Moscow",
  "Ukraine": "Europe/Kiev",
  "Romania": "Europe/Bucharest",
  "Hungary": "Europe/Budapest",
  "Bulgaria": "Europe/Sofia",
  "Serbia": "Europe/Belgrade",
  "Croatia": "Europe/Zagreb",
  "Turkey": "Europe/Istanbul",
  "China": "Asia/Shanghai",
  "Japan": "Asia/Tokyo",
  "South Korea": "Asia/Seoul",
  "India": "Asia/Kolkata",
  "Pakistan": "Asia/Karachi",
  "Bangladesh": "Asia/Dhaka",
  "Indonesia": "Asia/Jakarta",
  "Thailand": "Asia/Bangkok",
  "Vietnam": "Asia/Ho_Chi_Minh",
  "Philippines": "Asia/Manila",
  "Malaysia": "Asia/Kuala_Lumpur",
  "Singapore": "Asia/Singapore",
  "Hong Kong": "Asia/Hong_Kong",
  "Taiwan": "Asia/Taipei",
  "Israel": "Asia/Jerusalem",
  "Saudi Arabia": "Asia/Riyadh",
  "United Arab Emirates": "Asia/Dubai",
  "Qatar": "Asia/Qatar",
  "Kuwait": "Asia/Kuwait",
  "Iran": "Asia/Tehran",
  "Iraq": "Asia/Baghdad",
  "Australia": "Australia/Sydney",
  "New Zealand": "Pacific/Auckland",
  "South Africa": "Africa/Johannesburg",
  "Egypt": "Africa/Cairo",
  "Nigeria": "Africa/Lagos",
  "Kenya": "Africa/Nairobi",
  "Morocco": "Africa/Casablanca",
  "Algeria": "Africa/Algiers",
  "Tunisia": "Africa/Tunis",
  "Ghana": "Africa/Accra",
  "Ethiopia": "Africa/Addis_Ababa",
  "Zimbabwe": "Africa/Harare",
  "Angola": "Africa/Luanda",
  "Mozambique": "Africa/Maputo",
};

/**
 * Get the default timezone for a country
 * @param country - Country name
 * @returns Timezone string or empty string if not found
 */
export function getTimezoneForCountry(country: string): string {
  return COUNTRY_TIMEZONE_MAP[country] || "";
}
