// Shared testimonials data used across the application
// Hero testimonials and main testimonial section will both use this data
// but maintain their distinct styling

export interface TestimonialData {
  name: string;
  role: string;
  text: string;
  rating: number;
  avatar: string;
  image: string;
  country?: string;
}

export const allTestimonials: TestimonialData[] = [
  // Original hero testimonials
  {
    name: "Sarah Mitchell",
    role: "Day Trader",
    text: "M4Capital transformed my trading experience. The platform is incredibly intuitive and the execution speed is unmatched!",
    rating: 5,
    avatar: "SM",
    image: "/avatars/avatar-1.jpg",
    country: "USA",
  },
  {
    name: "John Davis",
    role: "Crypto Investor",
    text: "Outstanding customer support and the best spreads I've found. Highly recommend for serious traders.",
    rating: 5,
    avatar: "JD",
    image: "/avatars/avatar-2.jpg",
    country: "USA",
  },
  {
    name: "Emily Chen",
    role: "Portfolio Manager",
    text: "Professional-grade tools with retail-friendly pricing. Been using M4Capital for 2 years now!",
    rating: 5,
    avatar: "EC",
    image: "/avatars/avatar-3.jpg",
    country: "China",
  },
  // Original testimonial section testimonials
  {
    name: "Liam Johnson",
    role: "Full-time Trader",
    text: "This platform has completely changed the way I trade. The insights and tools are top-notch.",
    rating: 5,
    avatar: "LJ",
    image: "/avatars/avatar-4.jpg",
    country: "USA",
  },
  {
    name: "Sophie Müller",
    role: "Financial Analyst",
    text: "An essential tool for any serious forex trader. The real-time data is incredibly accurate.",
    rating: 5,
    avatar: "SM",
    image: "/avatars/avatar-5.jpg",
    country: "Germany",
  },
  {
    name: "Kenji Tanaka",
    role: "Hobbyist Investor",
    text: "I've seen a significant improvement in my trading performance since I started using this service.",
    rating: 4,
    avatar: "KT",
    image: "/avatars/avatar-6.jpg",
    country: "Japan",
  },
  {
    name: "Olivia Smith",
    role: "Beginner Trader",
    text: "The user interface is so intuitive. I was able to get started in minutes.",
    rating: 4,
    avatar: "OS",
    image: "/avatars/avatar-7.jpg",
    country: "United Kingdom",
  },
  {
    name: "Lucas Costa",
    role: "Portfolio Manager",
    text: "Customer support is fantastic. They are always quick to respond and very helpful.",
    rating: 5,
    avatar: "LC",
    image: "/avatars/avatar-8.jpg",
    country: "Brazil",
  },
  {
    name: "Noah Tremblay",
    role: "Day Trader",
    text: "The low latency execution has saved me a lot of money on slippage.",
    rating: 5,
    avatar: "NT",
    image: "/avatars/avatar-9.jpg",
    country: "Canada",
  },
  {
    name: "Priya Sharma",
    role: "Social Trader",
    text: "I love the community features. It's great to be able to share strategies with other traders.",
    rating: 4,
    avatar: "PS",
    image: "/avatars/avatar-10.jpg",
    country: "India",
  },
  {
    name: "David Okoro",
    role: "Technical Analyst",
    text: "The analytics are powerful yet easy to understand. A game-changer for my strategy.",
    rating: 5,
    avatar: "DO",
    image: "/avatars/avatar-11.jpg",
    country: "Nigeria",
  },
  {
    name: "Chloe Williams",
    role: "Long-term Investor",
    text: "Secure, fast, and reliable. Everything I need in a trading platform.",
    rating: 5,
    avatar: "CW",
    image: "/avatars/avatar-12.jpg",
    country: "Australia",
  },
  {
    name: "Mateo Garcia",
    role: "Remote Trader",
    text: "The mobile app is just as powerful as the desktop version. I can trade on the go.",
    rating: 4,
    avatar: "MG",
    image: "/avatars/avatar-13.jpg",
    country: "Mexico",
  },
  {
    name: "Léa Dubois",
    role: "Financial Advisor",
    text: "Finally, a platform that puts the user first. Highly recommended.",
    rating: 5,
    avatar: "LD",
    image: "/avatars/avatar-14.jpg",
    country: "France",
  },
  {
    name: "Min-jun Kim",
    role: "New Investor",
    text: "The educational resources helped me get up to speed with advanced trading concepts.",
    rating: 5,
    avatar: "MK",
    image: "/avatars/avatar-15.jpg",
    country: "South Korea",
  },
  {
    name: "Sofia Rossi",
    role: "Scalper",
    text: "I've tried many platforms, and this is by far the best. The execution speed is unmatched.",
    rating: 5,
    avatar: "SR",
    image: "/avatars/avatar-16.jpg",
    country: "Italy",
  },
  {
    name: "Carlos Fernández",
    role: "Global Macro Trader",
    text: "The variety of available currency pairs is impressive.",
    rating: 4,
    avatar: "CF",
    image: "/avatars/avatar-17.jpg",
    country: "Spain",
  },
  {
    name: "Thabo Zulu",
    role: "Retail Investor",
    text: "A trustworthy platform with transparent pricing. No hidden fees.",
    rating: 5,
    avatar: "TZ",
    image: "/avatars/avatar-18.jpg",
    country: "South Africa",
  },
  {
    name: "Ivan Petrov",
    role: "Chartist",
    text: "The charting tools are incredibly advanced and customizable.",
    rating: 5,
    avatar: "IP",
    image: "/avatars/avatar-19.jpg",
    country: "Russia",
  },
  {
    name: "Emma Johansson",
    role: "Growth Investor",
    text: "This platform has given me the confidence to take my trading to the next level.",
    rating: 5,
    avatar: "EJ",
    image: "/avatars/avatar-20.jpg",
    country: "Sweden",
  },
  {
    name: "Pablo Torres",
    role: "FX Trader",
    text: "The withdrawal process is fast and hassle-free. I got my funds in less than a day.",
    rating: 4,
    avatar: "PT",
    image: "/avatars/avatar-1.jpg",
    country: "Argentina",
  },
  {
    name: "Anna de Vries",
    role: "Risk Manager",
    text: "I appreciate the focus on security. I feel safe trading here.",
    rating: 5,
    avatar: "AV",
    image: "/avatars/avatar-2.jpg",
    country: "Netherlands",
  },
  {
    name: "Wei Chen",
    role: "Algo Trader",
    text: "The best platform for automated trading strategies. The API is robust and well-documented.",
    rating: 4,
    avatar: "WC",
    image: "/avatars/avatar-3.jpg",
    country: "China",
  },
];
