import { NextRequest, NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

export const dynamic = "force-dynamic";

/**
 * POST /api/telegram/link
 * This endpoint is not used - link codes are generated by the Telegram bot using /link command
 * Keeping for backwards compatibility
 */
export async function POST(request: NextRequest) {
  try {
    const session = await getServerSession(authOptions);

    if (!session?.user?.id) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    return NextResponse.json(
      {
        error:
          "Please use the /link command in the Telegram bot to generate a linking code",
        botUsername: "@M4CapitalBot",
      },
      { status: 400 }
    );
  } catch (error) {
    console.error("Error in link endpoint:", error);
    return NextResponse.json(
      { error: "Failed to process request" },
      { status: 500 }
    );
  }
}

/**
 * PUT /api/telegram/link
 * Verify and link Telegram account using code
 */
export async function PUT(request: NextRequest) {
  try {
    const session = await getServerSession(authOptions);

    if (!session?.user?.id) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const body = await request.json();
    const { code } = body;

    console.log("🔗 Telegram Link Request:", {
      userId: session.user.id,
      code: code,
      timestamp: new Date().toISOString(),
    });

    if (!code) {
      return NextResponse.json({ error: "Code required" }, { status: 400 });
    }

    // Get the TelegramUser who generated this code
    const telegramUser = await prisma.telegramUser.findFirst({
      where: {
        linkCode: code,
        linkCodeExpiresAt: { gte: new Date() },
      },
      select: {
        telegramId: true,
        username: true,
        firstName: true,
        lastName: true,
        linkCodeExpiresAt: true,
      },
    });

    console.log(
      "📱 Telegram User Found:",
      telegramUser
        ? {
            telegramId: telegramUser.telegramId.toString(),
            username: telegramUser.username,
            expiresAt: telegramUser.linkCodeExpiresAt,
          }
        : "No user found"
    );

    if (!telegramUser) {
      // Check if code exists but expired
      const expiredUser = await prisma.telegramUser.findFirst({
        where: { linkCode: code },
        select: { linkCodeExpiresAt: true },
      });

      console.log(
        "⏰ Expired Code Check:",
        expiredUser
          ? {
              expiresAt: expiredUser.linkCodeExpiresAt,
              now: new Date().toISOString(),
            }
          : "Code not found in database"
      );

      return NextResponse.json(
        {
          error:
            "Invalid or expired code. Please generate a new code in Telegram using /link",
        },
        { status: 400 }
      );
    }

    // Link the Telegram account to the user
    await prisma.user.update({
      where: { id: session.user.id },
      data: {
        linkedTelegramId: telegramUser.telegramId,
        linkedTelegramUsername: telegramUser.username,
      },
    });

    // Clear the link code from TelegramUser
    await prisma.telegramUser.update({
      where: { telegramId: telegramUser.telegramId },
      data: {
        linkCode: null,
        linkCodeExpiresAt: null,
      },
    });

    console.log("✅ Telegram account linked successfully");

    return NextResponse.json({
      success: true,
      message: "Telegram account linked successfully",
      telegramUsername: telegramUser.username,
    });
  } catch (error) {
    console.error("❌ Error linking Telegram account:", error);
    return NextResponse.json(
      { error: "Failed to link Telegram account" },
      { status: 500 }
    );
  }
}

/**
 * GET /api/telegram/link
 * Check if user's Telegram is already linked
 */
export async function GET(request: NextRequest) {
  try {
    const session = await getServerSession(authOptions);

    if (!session?.user?.id) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    // Check if user has a linked Telegram account
    const user = await prisma.user.findUnique({
      where: { id: session.user.id },
      select: {
        linkedTelegramId: true,
        linkedTelegramUsername: true,
      },
    });

    const isLinked = !!user?.linkedTelegramId;

    return NextResponse.json({
      linked: isLinked,
      telegramUsername: user?.linkedTelegramUsername || null,
    });
  } catch (error) {
    console.error("Error checking link status:", error);
    return NextResponse.json(
      { error: "Failed to check link status" },
      { status: 500 }
    );
  }
}

/**
 * DELETE /api/telegram/link
 * Unlink Telegram account from user
 */
export async function DELETE(request: NextRequest) {
  try {
    const session = await getServerSession(authOptions);

    if (!session?.user?.id) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    // Unlink Telegram account
    await prisma.user.update({
      where: { id: session.user.id },
      data: {
        linkedTelegramId: null,
        linkedTelegramUsername: null,
      },
    });

    return NextResponse.json({
      success: true,
      message: "Telegram account unlinked successfully",
    });
  } catch (error) {
    console.error("Error unlinking Telegram account:", error);
    return NextResponse.json(
      { error: "Failed to unlink Telegram account" },
      { status: 500 }
    );
  }
}
